version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    restart: always
    volumes:
<<<<<<< HEAD
      - ./backup:/docker-entrypoint-initdb.d/
      # - "./.data/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chi101
      - MYSQL_USER=chi101
      - MYSQL_PASSWORD=chi101
=======
      - ./data:/var/lib/mysql
>>>>>>> 839d16979bb76e8c042abe6e0481c65526c26086
    ports:
      - 3307:3306
  app:
    build: ./
    container_name: app
    restart: always
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
