version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    networks:
      - chi101-net
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=chi101
      - MYSQL_PASSWORD=chi101
    restart: always
  app:
    build: ./
    container_name: app
    networks:
      - chi101-net
    volumes:
      - ./app/:/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
networks:
  chi101-net:
    driver: bridge
