version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    restart: always
    networks:
      - net
    volumes:
      - ./database:/database
      - ./data:/var/lib/mysql
  app:
    build: ./
    container_name: app
    restart: always
    networks:
      - net
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
networks:
  net:
    driver: bridge
